http:
  port: 28180
  adminPort: 28181
  gzip:
    enabled: false

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: TRACE

  # Logger-specific levels.
  loggers:
    "javax.management": WARN
    "org.eclipse.jetty": WARN
    "com.sun.jersey": WARN
    "org.hibernate": WARN
    "com.yammer.dropwizard.config": INFO
    "com.barchart.udt": WARN  
    "Kompics": WARN
    "se.sics.kompics": WARN
    "se.sics.dozy": INFO 
    "se.sics.gvod.stream.congestion.PullLedbat": WARN
    "se.sics.gvod.stream.report.ReportComp": INFO
    "se.sics.nat.stun.client.StunClientComp": WARN
    "NettyNetwork@30001": WARN
    "NettyNetwork@42003": WARN
    "NettyNetwork@40000": WARN
    "se.sics.ktoolbox.hops.managedStore.storage.HDFSHelper": DEBUG
    "se.sics.nstream.library.LibraryMngrComp": INFO
    "se.sics.nstream.torrent.TransferFSM": INFO
    "se.sics.nstream.hops.hdfs.HDFSComp": INFO
    "se.sics.nstream.hops.hdfs.HDFSHelper": INFO
    "se.sics.nstream.torrent.TorrentComp": INFO
    "se.sics.nutil.network.bestEffort.BestEffortNetworkComp": INFO
    "se.sics.nstream.torrent.transfer.DwnlConnComp": INFO
    "se.sics.nstream.torrent.transfer.UpldConnComp": INFO
    "se.sics.ktoolbox.util.network.ports.One2NChannel": INFO
    "se.sics.nstream.storage.cache.SimpleKCache": INFO
    "se.sics.nstream.storage.durable.disk.DiskComp": INFO
    "se.sics.ledbat.core.RTTEstimator": INFO
    "se.sics.nutil.tracking.load.NetworkQueueLoadProxy": INFO
    
  console:
      enabled: true

  file:
      enabled: true
      currentLogFilename: "vodRest.log"
      archivedLogFilenamePattern: "vodRest-%d{yyyy-mm-dd}.log.gz"