http:
  port: 28180
  adminPort: 28181
  gzip:
    enabled: false

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: TRACE

  # Logger-specific levels.
  loggers:
    "javax.management": WARN
    "org.eclipse.jetty": WARN
    "com.sun.jersey": WARN
    "org.hibernate": WARN
    "com.yammer.dropwizard.config": INFO
    "com.barchart.udt": WARN  
    "Kompics": WARN
    "se.sics.kompics": WARN
    "se.sics.dozy": INFO 
    "se.sics.gvod.stream.torrent.TorrentComp": INFO
    "se.sics.gvod.stream.congestion.PullLedbat": WARN
    "se.sics.gvod.stream.report.ReportComp": INFO
    "se.sics.nat.stun.client.StunClientComp": WARN
    "NettyNetwork@41003": WARN
    "NettyNetwork@42003": WARN
    "NettyNetwork@40000": WARN
    "se.sics.ktoolbox.hops.managedStore.storage.HDFSHelper": DEBUG
    "org.apache.hadoop.hdfs.DFSClient": TRACE
    
  console:
      enabled: true

  file:
      enabled: true
      currentLogFilename: "vodRest.log"
      archivedLogFilenamePattern: "vodRest-%d{yyyy-mm-dd}.log.gz"