server:
    type: simple
    applicationContextPath: /webapp
    adminContextPath: /admin
    connector:
        type: http
        port: 18080

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: TRACE
  # Logger-specific levels.
  loggers:
    "javax.management": WARN
    "org.eclipse.jetty": WARN
    "com.sun.jersey": WARN
    "org.hibernate": WARN
    "com.yammer.dropwizard.config": INFO
    "com.barchart.udt": WARN 
    "Kompics": WARN
    "se.sics.kompics": WARN
    "se.sics.dozy": INFO 
    "se.sics.gvod.stream.torrent.TorrentComp": INFO
    "se.sics.gvod.stream.congestion.PullLedbat": WARN
    "se.sics.gvod.stream.report.ReportComp": WARN
    "se.sics.nat.stun.client.StunClientComp": WARN
    "NettyNetwork@41002": WARN
    "NettyNetwork@42002": WARN
    "NettyNetwork@30000": WARN
    "se.sics.ktoolbox.hops.managedStore.storage.HDFSHelper": INFO
    "se.sics.dozy": DEBUG
    "se.sics.ktoolbox.hops.managedStore.storage.cache.HDFSReadCacheImpl": INFO
    "se.sics.nstream.library.LibraryMngrComp": INFO
    "se.sics.nstream.storage.cache.KCache": INFO
    "se.sics.nstream.torrent.TransferFSM": INFO
    "se.sics.nstream.hops.hdfs.HDFSComp": INFO
    "se.sics.nstream.hops.hdfs.HDFSHelper": INFO
    
  appenders:
      - type: console
      - type: file
        currentLogFilename: "dozyRest.log"
        archivedLogFilenamePattern: "dozyRest-%d{yyyy-mm-dd}.log"
        archivedFileCount: 10