server:
    type: simple
    applicationContextPath: /application
    adminContextPath: /admin
    connector:
        type: http
        port: 18080

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: TRACE

  # Logger-specific levels.
  loggers:
    "javax.management": WARN
    "org.eclipse.jetty": WARN
    "com.sun.jersey": WARN
    "org.hibernate": WARN
    "com.yammer.dropwizard.config": INFO
    
    "Kompics": WARN
    "se.sics.kompics": WARN
    "se.sics.dozy": INFO 
    "se.sics.nstream.library.LibraryMngrComp": INFO
    "org.apache.hadoop.hdfs.DFSClient": ERROR
    
  appenders:
      type: console

  appenders:
      type: file
      currentLogFilename: "dozyRest.log"
      archivedLogFilenamePattern: "dozyRest-%d{yyyy-mm-dd}.log"
      archivedFileCount: 10